doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App\User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/User'
                prefix: 'App\Entity\User'
                alias: AppUser
            App\Classe:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Classe'
                prefix: 'App\Entity\Classe'
                alias: AppClasse
            App\Race:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Race'
                prefix: 'App\Entity\Race'
                alias: AppRace
            App\Skill:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Skill'
                prefix: 'App\Entity\Skill'
                alias: AppSkill
            App\Specialty:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Specialty'
                prefix: 'App\Entity\Specialty'
                alias: AppSpecialty
            App\Spell:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Spell'
                prefix: 'App\Entity\Spell'
                alias: AppSpell
            App\Monster:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Monster'
                prefix: 'App\Entity\Monster'
                alias: AppMonster
            App\Talent:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Talent'
                prefix: 'App\Entity\Talent'
                alias: AppTalent
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
